spring:
  datasource:
    # HikariCP 连接池配置
    hikari:
      maximum-pool-size: 20 # 最大连接数
      minimum-idle: 5 # 最小空闲连接数
      idle-timeout: 30000 # 空闲连接超时时间
      connection-timeout: 20000 # 连接超时时间
      max-lifetime: 1800000 # 连接最大存活时间
      connection-test-query: SELECT 1 # 连接测试查询语句

# mysql数据库配置
DB_HOST: 113.45.27.27
DB_PORT: 3306
DB_NAME: springboot_db
DB_USERNAME: springboot_dev
DB_PASSWORD: Dev@springboot_114514!!!

