services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z # 全功能版本
    container_name: minio-unite-common              # 容器名称
    restart: unless-stopped     # 重启策略：除非手动停止，否则自动重启
    ports:
      - 9000:9000                 # API 端口（程序调用用）
      - 9001:9001                 # Console 端口（网页管理用）
    environment:
      MINIO_ROOT_USER: "minio-root"      # 管理员用户名
      MINIO_ROOT_PASSWORD: "123456789"   # 管理员密码
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ./minio/data:/data        # 数据持久化（重要！）
      - ./minio/config:/root/.minio
      - ./minio/logs:/var/log/minio
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "mc", "admin", "info", "local"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
